- name: variables grom inventory
  hosts: local
  connection: local
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello I am learning {{ COURSE }}, Learner  Is {{ LEARNER }}, Last date to complete course is {{ LAST_DATE }}"