- name: variables grom inventory
  hosts: frontend 
  tasks:
  - name: print course information #nome is not imp
    ansible.builtin.debug:
      msg: "Hello I am learning {{ COURSE }}, Trainer  Is {{ TRAINER }}, Duration: {{ DURATION }}"