- name: variables grom inventory
  hosts: frontend
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello I am learning {{ COURSE }}, Trainer  Is {{ TRAINER }}, Duration: {{ DURATION }}"