- name: understand vars preference
  hosts: local
  connection: local
  vars:
    GREETINGS: "Hello from PLAY"
  vars_files:
  - course.yaml
  vars_prompt:
  - name: GREETING
    prompt: Please enter the GREETING
    private: false 
  tasks:
  - name: print the greeting
    vars:
      GREETING "Hello FROM TASK"
    ansivle.builtin.debug:
      msg: "{{ GREETING }}"  