- name: install packages 
  hosts: frontend
  become: yes
  tasks: 
  - name: install packages
    ansible.builtin.package:
     name:
     state: installed
    loop:"{{ iten }}""
    - mysql
    - nginx
    - zip